from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session
from app.database.session import get_db
from app.services.report_service import report_service
from app.schemas.report import FinancialReportResponse, ReportCreateRequest
from typing import List

router = APIRouter()

@router.get("/", response_model=List[FinancialReportResponse])
def get_reports(db: Session = Depends(get_db)):
    return report_service.get_all_reports(db)

@router.post("/generate", response_model=FinancialReportResponse)
def generate_report(req: ReportCreateRequest, db: Session = Depends(get_db)):
    rep = report_service.create_report(
        db,
        title=req.report_title,
        rtype=req.report_type,
        summary=f"Automated financial report for {req.report_type} generated by AI Financial Architect.",
        fformat=req.file_format
    )
    return rep
