import html
import json
from typing import Dict, Any

try:
    import markdown as md_lib
    HAS_MARKDOWN_LIB = True
except ImportError:
    HAS_MARKDOWN_LIB = False
    md_lib = None

class ExportService:
    """Formatter service converting Markdown outputs to various export targets (Markdown, HTML, PDF, DOCX, Text, JSON)."""

    @staticmethod
    def to_markdown(content: str, title: str = "LifeOS Communication Report") -> str:
        return content

    @staticmethod
    def to_html(content: str, title: str = "LifeOS Communication Report") -> str:
        """Convert markdown to standalone styled HTML document."""
        if HAS_MARKDOWN_LIB and md_lib:
            html_body = md_lib.markdown(
                content,
                extensions=['tables', 'fenced_code', 'toc']
            )
        else:
            formatted = html.escape(content)
            formatted = formatted.replace('\n', '<br>')
            html_body = f"<div class='fallback-content'>{formatted}</div>"
        
        styled_html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{html.escape(title)}</title>
    <style>
        :root {{
            --bg-color: #0f172a;
            --card-bg: #1e293b;
            --text-color: #f8fafc;
            --text-muted: #94a3b8;
            --primary: #38bdf8;
            --border-color: #334155;
            --code-bg: #0f172a;
        }}
        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            background-color: var(--bg-color);
            color: var(--text-color);
            line-height: 1.6;
            margin: 0;
            padding: 40px 20px;
        }}
        .container {{
            max-width: 860px;
            margin: 0 auto;
            background: var(--card-bg);
            border: 1px solid var(--border-color);
            border-radius: 12px;
            padding: 40px;
            box-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.5);
        }}
        h1, h2, h3, h4 {{
            color: #ffffff;
            border-bottom: 1px solid var(--border-color);
            padding-bottom: 8px;
            margin-top: 24px;
        }}
        h1 {{ color: var(--primary); font-size: 2rem; }}
        h2 {{ font-size: 1.5rem; color: #e2e8f0; }}
        code {{
            background-color: var(--code-bg);
            color: #38bdf8;
            padding: 2px 6px;
            border-radius: 4px;
            font-family: "Fira Code", monospace;
            font-size: 0.9em;
        }}
        pre {{
            background-color: var(--code-bg);
            padding: 16px;
            border-radius: 8px;
            overflow-x: auto;
            border: 1px solid var(--border-color);
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }}
        th, td {{
            padding: 12px 16px;
            border: 1px solid var(--border-color);
            text-align: left;
        }}
        th {{ background-color: #0f172a; color: var(--primary); }}
        blockquote {{
            border-left: 4px solid var(--primary);
            margin: 0;
            padding-left: 16px;
            color: var(--text-muted);
        }}
        ul, ol {{ padding-left: 24px; }}
        li {{ margin-bottom: 6px; }}
        .footer {{
            margin-top: 40px;
            text-align: center;
            font-size: 0.85rem;
            color: var(--text-muted);
            border-top: 1px solid var(--border-color);
            padding-top: 16px;
        }}
    </style>
</head>
<body>
    <div class="container">
        {html_body}
        <div class="footer">
            Generated by <strong>LifeOS Communication Agent</strong>
        </div>
    </div>
</body>
</html>"""
        return styled_html

    @classmethod
    def to_pdf_html(cls, content: str, title: str = "LifeOS Communication Report") -> str:
        """HTML representation configured for print / PDF print-to-file rendering."""
        return cls.to_html(content, title=title)

    @staticmethod
    def to_docx_text(content: str, title: str = "LifeOS Communication Report") -> str:
        """Format text clean document suitable for DOCX / Word export."""
        lines = content.split('\n')
        doc_lines = [f"=== {title.upper()} ===", ""]
        for line in lines:
            if line.startswith('#'):
                doc_lines.append(f"\n{line.lstrip('#').strip().upper()}")
                doc_lines.append('-' * 40)
            else:
                doc_lines.append(line.replace('**', '').replace('`', ''))
        return '\n'.join(doc_lines)

    @staticmethod
    def to_email_text(content: str) -> str:
        """Convert markdown text to clean text suitable for email body."""
        lines = content.split('\n')
        clean_lines = []
        for line in lines:
            if line.startswith('#'):
                clean_lines.append('\n' + line.lstrip('#').strip().upper())
                clean_lines.append('=' * len(line.lstrip('#').strip()))
            elif line.startswith('**') and line.endswith('**'):
                clean_lines.append(line.replace('**', ''))
            else:
                clean_lines.append(line.replace('**', '').replace('`', ''))
        return '\n'.join(clean_lines)

export_service = ExportService()
