import json
from typing import Dict, Any, List, Optional
from app.schemas.review import IssueItem, StandardReviewOutput, QualityScoreBreakdown
from app.validators.json_validator import JSONValidator
from app.validators.code_validator import CodeValidator
from app.validators.doc_validator import DocumentValidator
from app.validators.ai_validator import AIValidator
from app.validators.memory_validator import MemoryValidator
from app.validators.execution_validator import ExecutionValidator
from app.validators.comms_validator import CommunicationValidator
from app.validators.research_validator import ResearchValidator
from app.validators.planning_validator import PlanningValidator
from app.validators.chief_of_staff_validator import ChiefOfStaffValidator
from app.ai.gemini_client import gemini_client
from app.core.scoring import QualityScorer
from app.core.logger import logger

class ReviewAgent:
    """
    Main Quality Assurance Agent for the LifeOS Multi-Agent Ecosystem.
    Validates, reviews, verifies, and scores outputs generated by all agents
    (Research Agent, Planning Agent, Memory Agent, Execution Agent, Communication Agent, Chief of Staff).
    """

    async def execute_review(
        self,
        agent_name: str,
        review_type: str,
        content: Any,
        metadata: Optional[Dict[str, Any]] = None
    ) -> StandardReviewOutput:
        """Executes a full QA review pipeline."""

        issues: List[IssueItem] = []
        warnings: List[str] = []
        suggestions: List[str] = []
        base_deduction = 0.0

        content_str = json.dumps(content) if isinstance(content, (dict, list)) else str(content)

        # 1. Specialized Validator Execution based on review type or agent name
        rtype = review_type.lower()
        aname = agent_name.lower()

        # Code Review
        if "code" in rtype or "code" in aname:
            lang = metadata.get("language", "python") if metadata else "python"
            c_issues, c_warns, c_suggs, c_deduct = CodeValidator.validate(content_str, language=lang)
            issues.extend(c_issues)
            warnings.extend(c_warns)
            suggestions.extend(c_suggs)
            base_deduction += c_deduct

        # JSON Review
        if "json" in rtype or isinstance(content, dict):
            req_keys = metadata.get("required_keys") if metadata else None
            schema_def = metadata.get("schema_definition") if metadata else None
            _, j_issues, j_warns, j_suggs, j_deduct = JSONValidator.validate(
                content, required_keys=req_keys, schema_definition=schema_def
            )
            issues.extend(j_issues)
            warnings.extend(j_warns)
            suggestions.extend(j_suggs)
            base_deduction += j_deduct

        # Document / Markdown Review
        if any(w in rtype for w in ["document", "markdown", "report", "summary"]):
            doc_kind = metadata.get("document_type", "markdown") if metadata else "markdown"
            d_issues, d_warns, d_suggs, d_deduct = DocumentValidator.validate(content_str, document_type=doc_kind)
            issues.extend(d_issues)
            warnings.extend(d_warns)
            suggestions.extend(d_suggs)
            base_deduction += d_deduct

        # Domain specific agent checks
        if "memory" in aname or "memory" in rtype:
            if isinstance(content, dict):
                m_issues, m_warns, m_suggs, m_deduct = MemoryValidator.validate(content)
                issues.extend(m_issues)
                warnings.extend(m_warns)
                suggestions.extend(m_suggs)
                base_deduction += m_deduct

        elif "execution" in aname or "execution" in rtype:
            exec_kind = metadata.get("execution_type", "api_call") if metadata else "api_call"
            e_issues, e_warns, e_suggs, e_deduct = ExecutionValidator.validate(exec_kind, content)
            issues.extend(e_issues)
            warnings.extend(e_warns)
            suggestions.extend(e_suggs)
            base_deduction += e_deduct

        elif "communication" in aname or "communication" in rtype or "comm" in rtype:
            comm_kind = metadata.get("comm_type", "email") if metadata else "email"
            cm_issues, cm_warns, cm_suggs, cm_deduct = CommunicationValidator.validate(content_str, comm_type=comm_kind)
            issues.extend(cm_issues)
            warnings.extend(cm_warns)
            suggestions.extend(cm_suggs)
            base_deduction += cm_deduct

        elif "research" in aname or "research" in rtype:
            srcs = metadata.get("sources", []) if metadata else []
            r_issues, r_warns, r_suggs, r_deduct = ResearchValidator.validate(content_str, sources=srcs)
            issues.extend(r_issues)
            warnings.extend(r_warns)
            suggestions.extend(r_suggs)
            base_deduction += r_deduct

        elif "planning" in aname or "planning" in rtype:
            goal = metadata.get("goal", "Agent Task Goal") if metadata else "Agent Task Goal"
            mstones = metadata.get("milestones", []) if metadata else []
            p_issues, p_warns, p_suggs, p_deduct = PlanningValidator.validate(goal, content, milestones=mstones)
            issues.extend(p_issues)
            warnings.extend(p_warns)
            suggestions.extend(p_suggs)
            base_deduction += p_deduct

        elif "chief" in aname or "staff" in aname or "chief" in rtype:
            delegated = metadata.get("delegated_agents", []) if metadata else []
            cos_issues, cos_warns, cos_suggs, cos_deduct = ChiefOfStaffValidator.validate(content, delegated_agents=delegated)
            issues.extend(cos_issues)
            warnings.extend(cos_warns)
            suggestions.extend(cos_suggs)
            base_deduction += cos_deduct

        # General AI & Hallucination Check
        ai_issues, ai_warns, ai_suggs, ai_deduct = AIValidator.validate(content_str)
        issues.extend(ai_issues)
        warnings.extend(ai_warns)
        suggestions.extend(ai_suggs)
        base_deduction += ai_deduct

        # 2. Call Gemini AI Client for Deep AI Reasoning if Key Provided
        gemini_result = await gemini_client.review_content(agent_name, review_type, content, metadata)
        if gemini_result and isinstance(gemini_result, dict):
            # Merge Gemini findings
            g_issues = gemini_result.get("issues", [])
            for gi in g_issues:
                if isinstance(gi, dict):
                    issues.append(IssueItem(
                        code=gi.get("code", "AI_QA_ISSUE"),
                        severity=gi.get("severity", "medium"),
                        message=gi.get("message", "AI detected issue"),
                        field=gi.get("field"),
                        suggestion=gi.get("suggestion")
                    ))
            g_warns = gemini_result.get("warnings", [])
            warnings.extend([w for w in g_warns if isinstance(w, str)])
            g_suggs = gemini_result.get("suggestions", [])
            suggestions.extend([s for s in g_suggs if isinstance(s, str)])

        # 3. Deduplicate warnings and suggestions
        warnings = list(dict.fromkeys(warnings))
        suggestions = list(dict.fromkeys(suggestions))

        # 4. Calculate Final Quality Score, Confidence, Status & Breakdown
        score, confidence, status, breakdown = QualityScorer.calculate_score(
            issues, warnings, base_deductions=base_deduction
        )

        tier = QualityScorer.get_tier(score)
        summary = (
            f"Review completed for {agent_name} ({review_type}). "
            f"Quality Score: {score}/100 ({tier}). "
            f"Status: {status.upper()}. "
            f"Total issues: {len(issues)}, warnings: {len(warnings)}."
        )

        return StandardReviewOutput(
            status=status,
            quality_score=score,
            confidence=confidence,
            issues=issues,
            warnings=warnings,
            suggestions=suggestions,
            summary=summary,
            score_breakdown=breakdown
        )

review_agent = ReviewAgent()
