from sqlalchemy.orm import Session
from app.models.report import FinancialReport
import uuid
import datetime

class ReportService:
    def get_all_reports(self, db: Session):
        reports = db.query(FinancialReport).order_by(FinancialReport.created_at.desc()).all()
        if not reports:
            # Seed default reports
            defaults = [
                {"title": "Q3 2026 Executive Financial Summary", "type": "Executive Summary", "summary": "Comprehensive overview of Q3 cloud infrastructure, AI model token costs, and engineering velocity."},
                {"title": "SaaS AI Copilot Cost Breakdown Report", "type": "Project Cost Report", "summary": "Detailed itemization of 24 line items including frontend, backend, vector DB, and devops."},
                {"title": "Multi-Cloud Infrastructure Audit (AWS vs Supabase)", "type": "Infrastructure Cost Report", "summary": "Side-by-side pricing audit demonstrating a 32% cost optimization potential by migrating databases."},
                {"title": "3-Year Product ROI & Break-even Statement", "type": "ROI Report", "summary": "Financial ROI projection indicating payback period of 14 months and 184% 3-year return."}
            ]
            for d in defaults:
                rep = FinancialReport(
                    id=str(uuid.uuid4()),
                    report_title=d["title"],
                    report_type=d["type"],
                    author="AI Financial Architect",
                    summary=d["summary"],
                    report_data={"status": "Final Approved", "generated_by": "Enterprise Finance Agent"},
                    file_format="PDF"
                )
                db.add(rep)
            db.commit()
            reports = db.query(FinancialReport).all()
        return reports

    def create_report(self, db: Session, title: str, rtype: str, summary: str = "", rdata: dict = None, fformat: str = "PDF"):
        rep = FinancialReport(
            id=str(uuid.uuid4()),
            report_title=title,
            report_type=rtype,
            author="AI Financial Architect",
            summary=summary or f"Automated {rtype} generated by AI Financial Architect.",
            report_data=rdata or {"status": "Generated"},
            file_format=fformat
        )
        db.add(rep)
        db.commit()
        db.refresh(rep)
        return rep

report_service = ReportService()
