import React, { useState, useEffect } from 'react';
import { History, Search, Trash2, FileText, Mail, Sparkles, Clock, CheckCircle2, Eye, X } from 'lucide-react';
import { HistoryEvent } from '../utils/historyLogger';

export const CommunicationHistoryView: React.FC = () => {
  const [historyEvents, setHistoryEvents] = useState<HistoryEvent[]>([]);
  const [search, setSearch] = useState<string>('');
  const [filterType, setFilterType] = useState<string>('all');
  const [selectedEvent, setSelectedEvent] = useState<HistoryEvent | null>(null);

  const loadHistory = () => {
    const saved = localStorage.getItem('lifeos_comm_history');
    if (saved) {
      try {
        setHistoryEvents(JSON.parse(saved));
      } catch (e) {
        setHistoryEvents([]);
      }
    } else {
      setHistoryEvents([]);
    }
  };

  useEffect(() => {
    loadHistory();
  }, []);

  const handleClearHistory = () => {
    setHistoryEvents([]);
    localStorage.removeItem('lifeos_comm_history');
    setSelectedEvent(null);
  };

  const handleDeleteEvent = (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    const updated = historyEvents.filter((item) => item.id !== id);
    setHistoryEvents(updated);
    localStorage.setItem('lifeos_comm_history', JSON.stringify(updated));
    if (selectedEvent?.id === id) {
      setSelectedEvent(null);
    }
  };

  const filteredEvents = historyEvents.filter((item) => {
    const matchesFilter = filterType === 'all' || item.type === filterType;
    const matchesSearch =
      item.title.toLowerCase().includes(search.toLowerCase()) ||
      item.preview.toLowerCase().includes(search.toLowerCase()) ||
      item.details.toLowerCase().includes(search.toLowerCase());
    return matchesFilter && matchesSearch;
  });

  return (
    <div className="space-y-6">
      {/* Top Banner Header */}
      <div className="p-6 rounded-2xl bg-gradient-to-r from-slate-900 via-indigo-950/60 to-purple-950/60 border border-indigo-500/30 shadow-xl flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <span className="px-3 py-1 rounded-full bg-indigo-500/20 text-indigo-300 text-xs font-mono font-bold border border-indigo-500/30 flex items-center gap-1.5">
              <History className="w-3.5 h-3.5 text-indigo-400" />
              User Communication Activity History
            </span>
          </div>
          <h1 className="text-xl font-extrabold text-slate-100 mt-2 tracking-tight">
            Event History & Audit Trail
          </h1>
          <p className="text-xs text-slate-400 mt-1 max-w-2xl">
            Real chronological history of activities generated by you in AI Text Simplifier, Generate Report, and Generate Email.
          </p>
        </div>

        {historyEvents.length > 0 && (
          <button
            onClick={handleClearHistory}
            className="px-4 py-2 rounded-xl bg-rose-500/20 hover:bg-rose-500/30 text-rose-300 border border-rose-500/40 text-xs font-bold transition-all flex items-center gap-1.5"
          >
            <Trash2 className="w-3.5 h-3.5" />
            <span>Clear History Log</span>
          </button>
        )}
      </div>

      {/* Filter and Search Bar */}
      <div className="glass-panel p-4 rounded-2xl border border-slate-800 flex flex-col sm:flex-row items-center justify-between gap-4">
        <div className="flex bg-slate-950 border border-slate-800 rounded-xl p-1 text-xs w-full sm:w-auto">
          {[
            { id: 'all', label: 'All Events' },
            { id: 'simplifier', label: 'Simplifications' },
            { id: 'report', label: 'Reports' },
            { id: 'email', label: 'Emails' }
          ].map((tab) => (
            <button
              key={tab.id}
              onClick={() => setFilterType(tab.id)}
              className={`px-3 py-1.5 rounded-lg font-semibold transition-colors flex-1 sm:flex-none text-center ${
                filterType === tab.id
                  ? 'bg-indigo-600 text-white shadow-sm'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              {tab.label}
            </button>
          ))}
        </div>

        <div className="relative w-full sm:w-72">
          <Search className="w-4 h-4 absolute left-3 top-2.5 text-slate-500" />
          <input
            type="text"
            placeholder="Search event history..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="w-full bg-slate-950 border border-slate-800 text-xs rounded-xl pl-9 pr-3 py-2 text-slate-200 focus:outline-none focus:border-indigo-500"
          />
        </div>
      </div>

      {/* Events Grid + Viewer Split Screen */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Event Cards List */}
        <div className="lg:col-span-6 space-y-3">
          {filteredEvents.length === 0 ? (
            <div className="glass-panel p-12 text-center text-slate-500 rounded-2xl border border-slate-800 space-y-2">
              <History className="w-8 h-8 text-slate-600 mx-auto" />
              <h4 className="text-sm font-bold text-slate-300">No History Events Found</h4>
              <p className="text-xs text-slate-400">
                Use AI Text Simplifier, Generate Report, or Generate Email to log your real activity here.
              </p>
            </div>
          ) : (
            filteredEvents.map((event) => {
              const isSelected = selectedEvent?.id === event.id;
              let EventIcon = Sparkles;
              let iconColor = 'text-sky-400 bg-sky-500/20';

              if (event.type === 'report') {
                EventIcon = FileText;
                iconColor = 'text-emerald-400 bg-emerald-500/20';
              } else if (event.type === 'email') {
                EventIcon = Mail;
                iconColor = 'text-indigo-400 bg-indigo-500/20';
              }

              return (
                <div
                  key={event.id}
                  onClick={() => setSelectedEvent(event)}
                  className={`p-4 rounded-2xl border cursor-pointer transition-all relative group flex flex-col justify-between space-y-2 ${
                    isSelected
                      ? 'bg-indigo-950/40 border-indigo-500/60 shadow-lg shadow-indigo-500/10'
                      : 'bg-slate-900/60 border-slate-800 hover:border-slate-700 hover:bg-slate-900'
                  }`}
                >
                  <div className="flex items-start justify-between gap-3">
                    <div className="flex items-center gap-3">
                      <div className={`p-2 rounded-xl shrink-0 ${iconColor}`}>
                        <EventIcon className="w-4 h-4" />
                      </div>
                      <div>
                        <h3 className="text-xs font-bold text-slate-100">{event.title}</h3>
                        <span className="text-[10px] text-slate-400 font-mono">{event.details}</span>
                      </div>
                    </div>

                    <div className="flex items-center gap-2 shrink-0">
                      <span className="text-[10px] text-slate-500 font-mono flex items-center gap-1">
                        <Clock className="w-3 h-3" />
                        {event.timestamp}
                      </span>

                      <button
                        onClick={(e) => handleDeleteEvent(event.id, e)}
                        className="p-1 rounded-lg text-slate-500 hover:text-rose-400 hover:bg-slate-800 transition"
                        title="Delete event"
                      >
                        <Trash2 className="w-3.5 h-3.5" />
                      </button>
                    </div>
                  </div>

                  <p className="text-xs text-slate-300 line-clamp-2 bg-slate-950/60 p-2.5 rounded-xl border border-slate-800/80 font-sans leading-relaxed">
                    {event.preview}
                  </p>
                </div>
              );
            })
          )}
        </div>

        {/* Selected Event Details Panel */}
        <div className="lg:col-span-6">
          <div className="glass-panel p-6 rounded-2xl border border-indigo-500/30 bg-slate-950/80 space-y-4">
            {selectedEvent ? (
              <div className="space-y-4">
                <div className="flex items-center justify-between pb-3 border-b border-slate-800">
                  <div>
                    <span className="px-2.5 py-0.5 rounded-full bg-indigo-500/20 text-indigo-300 border border-indigo-500/30 text-[10px] font-mono font-bold">
                      {selectedEvent.badge}
                    </span>
                    <h3 className="text-base font-bold text-slate-100 mt-1">{selectedEvent.title}</h3>
                    <span className="text-[11px] text-slate-400 font-mono">Timestamp: {selectedEvent.timestamp}</span>
                  </div>

                  <button
                    onClick={() => setSelectedEvent(null)}
                    className="p-1 rounded-lg text-slate-400 hover:text-slate-200"
                  >
                    <X className="w-4 h-4" />
                  </button>
                </div>

                <div className="space-y-2">
                  <span className="text-[10px] uppercase font-bold text-indigo-400 tracking-wider">Event Parameters</span>
                  <div className="p-3 rounded-xl bg-slate-900 border border-slate-800 text-xs text-slate-300 font-mono">
                    {selectedEvent.details}
                  </div>
                </div>

                <div className="space-y-2">
                  <span className="text-[10px] uppercase font-bold text-emerald-400 tracking-wider">Event Content Snapshot</span>
                  <div className="p-4 rounded-xl bg-slate-900 border border-slate-800 text-xs text-slate-200 whitespace-pre-line leading-relaxed font-sans max-h-96 overflow-y-auto">
                    {selectedEvent.preview}
                  </div>
                </div>

                <div className="pt-2 flex justify-end">
                  <button
                    onClick={() => navigator.clipboard.writeText(selectedEvent.preview)}
                    className="px-3.5 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white font-bold text-xs shadow-md shadow-indigo-500/20 transition-all flex items-center gap-1.5"
                  >
                    <CheckCircle2 className="w-3.5 h-3.5" />
                    <span>Copy Content</span>
                  </button>
                </div>
              </div>
            ) : (
              <div className="h-64 flex flex-col items-center justify-center text-slate-500 space-y-2">
                <Eye className="w-8 h-8 text-slate-600" />
                <p className="text-xs">Click on any event from the left log to view full details</p>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};
