from typing import List, Dict, Any, Optional
from datetime import datetime
from pydantic import BaseModel, Field, ConfigDict

class IssueItem(BaseModel):
    code: str = Field(..., description="Short error code/identifier")
    severity: str = Field("medium", description="critical, high, medium, low, info")
    message: str = Field(..., description="Human readable issue description")
    field: Optional[str] = Field(None, description="Field, line number or section where issue was detected")
    suggestion: Optional[str] = Field(None, description="Actionable suggestion for fix")

class QualityScoreBreakdown(BaseModel):
    accuracy: float = 100.0
    completeness: float = 100.0
    consistency: float = 100.0
    correctness: float = 100.0
    formatting: float = 100.0
    grammar: float = 100.0
    structure: float = 100.0
    security: float = 100.0
    performance: float = 100.0
    maintainability: float = 100.0
    compliance: float = 100.0
    overall_score: float = 100.0

class StandardReviewOutput(BaseModel):
    status: str = Field(..., description="'approved' or 'rejected'")
    quality_score: float = Field(..., description="0 to 100 quality score")
    confidence: float = Field(0.95, description="0.0 to 1.0 confidence score")
    issues: List[IssueItem] = Field(default_factory=list)
    warnings: List[str] = Field(default_factory=list)
    suggestions: List[str] = Field(default_factory=list)
    summary: str = Field("", description="Overall review summary")
    score_breakdown: Optional[QualityScoreBreakdown] = None

class GenericReviewCreate(BaseModel):
    agent_name: str = Field(..., description="Target Agent (Research Agent, Planning Agent, Memory Agent, Execution Agent, Communication Agent, Chief of Staff)")
    review_type: str = Field("Response Review", description="Review type name")
    content: Any = Field(..., description="The content/payload generated by the target agent to be reviewed")
    metadata: Optional[Dict[str, Any]] = Field(default_factory=dict)
    rules: Optional[List[str]] = Field(default=None, description="Optional custom validation rules")

class CodeReviewCreate(BaseModel):
    agent_name: str = Field("Execution Agent")
    language: str = Field("python", description="python, java, javascript, typescript, html, css, sql")
    code: str = Field(..., description="Code snippet or file content to review")
    context: Optional[str] = Field(None, description="Context or requirement description for code")

class JSONReviewCreate(BaseModel):
    agent_name: str = Field("Execution Agent")
    json_data: Any = Field(..., description="Raw JSON string or parsed JSON object")
    required_keys: Optional[List[str]] = Field(default=None)
    schema_definition: Optional[Dict[str, Any]] = Field(default=None)

class DocumentReviewCreate(BaseModel):
    agent_name: str = Field("Communication Agent")
    document_type: str = Field("markdown", description="markdown, pdf, text, report, research")
    content: str = Field(..., description="Document text content")
    title: Optional[str] = Field(None)

class ResearchReviewCreate(BaseModel):
    agent_name: str = Field("Research Agent")
    topic: str = Field(...)
    findings: str = Field(..., description="Research report content")
    sources: Optional[List[str]] = Field(default_factory=list)

class ExecutionReviewCreate(BaseModel):
    agent_name: str = Field("Execution Agent")
    execution_type: str = Field("api_call", description="generated_files, generated_reports, generated_apis, generated_code, database_scripts")
    output: Any = Field(...)

class PlanningReviewCreate(BaseModel):
    agent_name: str = Field("Planning Agent")
    goal: str = Field(...)
    plan: Any = Field(..., description="Structured plan content")
    milestones: Optional[List[Any]] = Field(default_factory=list)

class MemoryReviewCreate(BaseModel):
    agent_name: str = Field("Memory Agent")
    category: str = Field("User Preference", description="Memory category")
    tags: List[str] = Field(default_factory=list)
    importance_score: float = Field(0.8, description="0.0 to 1.0 importance score")
    summary: str = Field(..., description="Memory summary text")
    data: Optional[Dict[str, Any]] = Field(default_factory=dict)

class CommunicationReviewCreate(BaseModel):
    agent_name: str = Field("Communication Agent")
    comm_type: str = Field("email", description="email, meeting_notes, executive_summary")
    content: str = Field(..., description="Communication body content")
    subject: Optional[str] = Field(None)

class ChiefOfStaffReviewCreate(BaseModel):
    agent_name: str = Field("Chief of Staff")
    task_summary: str = Field(...)
    delegated_agents: Optional[List[str]] = Field(default_factory=list)
    content: Any = Field(..., description="Directive or task delegation payload")

class ReviewResponseRecord(BaseModel):
    id: str
    agent_name: str
    review_type: str
    input_data: Dict[str, Any]
    review_result: StandardReviewOutput
    quality_score: float
    confidence: float
    issues: List[Any]
    warnings: List[str]
    suggestions: List[str]
    status: str
    created_at: datetime
    updated_at: datetime

    model_config = ConfigDict(from_attributes=True)
